# Generated by Django 5.2 on 2025-04-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('kinematics', 'Кинематика'), ('dynamics', 'Динамика'), ('electro', 'Электродинамика')], max_length=20, verbose_name='Тема')),
                ('description', models.TextField(verbose_name='Условие задачи')),
                ('formula', models.CharField(max_length=100, verbose_name='Формула (LaTeX)')),
                ('answer', models.CharField(max_length=100, verbose_name='Ответ (SymPy-формат)')),
                ('difficulty', models.IntegerField(default=1, verbose_name='Сложность (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
