# Generated by Django 5.2 on 2025-04-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_alter_problem_answer_alter_problem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='topic',
            field=models.CharField(choices=[('Кинематика', 'Кинематика'), ('Динамика', 'Динамика')], max_length=20, verbose_name='Раздел'),
        ),
    ]
