# Generated by Django 5.2 on 2025-04-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_testsession_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsession',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='score',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='user',
        ),
        migrations.AlterField(
            model_name='testsession',
            name='topic',
            field=models.CharField(choices=[('kinematics', 'Только кинематика'), ('dynamics', 'Только динамика'), ('mixed', 'Смешанный тест')], default='mixed', max_length=20),
        ),
    ]
