# Generated by Django 5.2 on 2025-04-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_alter_testsession_options_testsession_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='topic',
            field=models.CharField(max_length=20),
        ),
    ]
