# Generated by Django 5.2 on 2025-04-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_alter_testsession_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsession',
            options={},
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='created_at',
        ),
        migrations.AddField(
            model_name='testsession',
            name='problem_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='problem',
            name='topic',
            field=models.CharField(choices=[('kinematics', 'Кинематика'), ('dynamics', 'Динамика')], max_length=20, verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='topic',
            field=models.CharField(choices=[('kinematics', 'Кинематика'), ('dynamics', 'Динамика'), ('mixed', 'Смешанный')], max_length=50, verbose_name='Тема'),
        ),
    ]
